import { Xanh_Mono, Geist } from "next/font/google";

import "./globals.css";

const geist = Geist({
  weight: "variable",
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const xahnMono = Xanh_Mono({
  weight: "400",
  variable: "--font-xahn-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body className={`${xahnMono.variable} ${geist.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
